apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: driver-deployment
spec:
  selector:
    matchLabels:
      app: driver
  replicas: 1
  template:
    metadata:
      labels:
        app: driver
    spec:
      containers:
      - name: driver
        image: yosaekiacr.azurecr.io/service_driver:20211107140617
        env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: zk-service:2181
