apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: optimizer-deployment
spec:
  selector:
    matchLabels:
      app: optimizer
  replicas: 1
  template:
    metadata:
      labels:
        app: optimizer
    spec:
      containers:
      - name: optimizer
        image: yosaekiacr.azurecr.io/service_optimizer:20211108024553
        env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: zk-service:2181
