apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: restaurant-deployment
spec:
  selector:
    matchLabels:
      app: restaurant
  replicas: 1
  template:
    metadata:
      labels:
        app: restaurant
    spec:
      containers:
      - name: restaurant
        image: yosaekiacr.azurecr.io/service_restaurant:20211108021128
        env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: zk-service:2181
