on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Get current datetime'
          id: datetime
          run: echo "::set-output name=datetime::$(date +'%Y%m%d%H%M%S')"

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            cd service_order/
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/service_order:${{ steps.datetime.outputs.datetime }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/service_order:${{ steps.datetime.outputs.datetime }}
            cd ../
            cd service_driver/
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/service_driver:${{ steps.datetime.outputs.datetime }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/service_driver:${{ steps.datetime.outputs.datetime }}
            cd ../
            cd service_restaurant/
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/service_restaurant:${{ steps.datetime.outputs.datetime }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/service_restaurant:${{ steps.datetime.outputs.datetime }}
            cd ../
            cd service_optimizer/
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/service_optimizer:${{ steps.datetime.outputs.datetime }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/service_optimizer:${{ steps.datetime.outputs.datetime }}

